systemProp.org.gradle.internal.publish.checksums.insecure=true

mavenCentralUsername=qJmYRiBC
mavenCentralPassword=tcYuxT3i33KzlMSNi7jdtKxmadG8ILhIAMQg5gSRhZdx

signing.keyId=8DA3749D
signing.password=1Joe@lisson
signing.secretKeyRingFile=/home/joealisson/.gnupg/secring.gpg

## ENV

#ORG_GRADLE_PROJECT_mavenCentralUsername=username
#ORG_GRADLE_PROJECT_mavenCentralPassword=the_password

# see below for how to obtain this
#ORG_GRADLE_PROJECT_signingInMemoryKey=exported_ascii_armored_key
# Optional
#ORG_GRADLE_PROJECT_signingInMemoryKeyId=12345678
# If key was created with a password.
#ORG_GRADLE_PROJECT_signingInMemoryKeyPassword=some_password
